### ISSUE TITLE
Studiojs functions for image processing works very slowly..

### ISSUE THREAD

**Issue by thinksysuser** [imazen/studiojs#14]
Hello,

I run the demo of Studiojs and found that each of it's functions shows very slow effects. For example, if I increase the brightness of the image, then it is applied to the image after 5-10 seconds of increasing the brightness. Is it possible to make it faster to shorten this time limit for rapid effect ?

Second issue, I found that if I completely applies my own effects to the image, then how can I save this image to desired folder ? No function present in the library to save this manipulated image?

**Comment by lilith** [comment]
StudioJS creates a command string. If you give this command string to ImageResizer, you can save a copy to a folder. 

If you are seeing high latency, it means your ImageResizer backend is running on underpowered hardware. Latency should never exceed 1s on reasonable hardware.
